### ISSUE TITLE
Internals should probably not be pub

### ISSUE THREAD

**Issue by taralx** [fizyk20/rust-gmp#3]
I noticed that the mpz_struct inside Mpz is public, but it really shouldn't be. It's not safe to modify the contents. If clients need access to the contents, there should be safe accessors instead.

**Comment by fizyk20** [comment]
While I agree it might not be the best design, I saw no better way of making it work with MPFR, where sometimes the bare mpz_struct is needed. An accessor might be more appropriate, but I felt it would just be unnecessary overhead, especially since it's just a wrapper around C where everything is public anyway.

**Comment by taralx** [comment]
Well, it's the rust principle -- the safe wrapper is supposed to be safe. For MPFR you could provide this:

``` rust
pub unsafe fn inner_mut(&mut self) -> *mut mpz_struct
```

**Comment by fizyk20** [comment]
Yeah, you're probably right - I'll fix it. Thanks :)
